service: srvrlss-site-blaubleu
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: "3"

custom:
  stage: ${opt:stage, self:provider.stage}
  # set tbl names:
  songsTable: ${self:custom.stage}-songs
  usersTable: ${self:custom.stage}-users
  artistsTable: ${self:custom.stage}-artists
  # set DynamoDB throughput for prod and np
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  # access secrets
  environment:  prod # ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    # SONGS_TBL: songs-${self:service}-${opt:stage, self:provider.stage} # this will result on: srvrlss-site-blaubleu-prod 
      # that is repo name + environement aka stage 
    SONGS_TBL: ${self:custom.songsTable}
    # USERS_TBL: users-${self:service}-${opt:stage, self:provider.stage}
    USERS_TBL: ${self:custom.usersTable}
    ARTISTS_TBL: ${self:custom.artistsTable}
    # ARTISTS_TBL: ${self:service}-${opt:stage, self:provider.stage}
    # PLAY_PLATFORM_TBL: ${self:service}-${opt:stage, self:provider.stage}
  iam.role.statements: # iamRoleStatements will be deprecated in v 4
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
        # "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SONGS_TBL}"
        - "Fn:GetAtt": [ SongsTable, Arn ]
        - "Fn:GetAtt": [ UsersTable, Arn ]
        - "Fn:GetAtt": [ ArtistsTable, Arn ]


resources:
  Resources:
    SongsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.SONGS_TBL}
        AttributeDefinitions:
          - AttributeName: song_id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: song_id
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        GlobalSecondaryIndexes:
          - IndexName: song_id-index
            KeySchema:
              - AttributeName: song_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.tableThroughput}
              WriteCapacityUnits: ${self:custom.tableThroughput}

    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USERS_TBL}
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: accessLevel
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: email
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ArtistsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.ARTISTS_TBL}
        AttributeDefinitions:
          - AttributeName: artist_id
            AttributeType: S
          - AttributeName: artistName
            AttributeType: S
          - AttributeName: instrument
            AttributeType: S
          - AttributeName: featured
            AttributeType: S
        KeySchema:
          - AttributeName: artist_id
            Keytype: HASH
          - AttributeName: featured
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: artist_id-index
          KeySchema:
            - AttributeName: artist_id
              KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: ${self:custom.tableThroughput}
              WriteCapacityUnits: ${self:custom.tableThroughput}

    # PlayPlatformTable:
      # Type: AWS::DynamoDB::Table
      # DeletionPolicy: Retain
      # Properties:
      #   TableName: ${self:provider.environment.PLAY_PLATFORM_TBL}
      #   AttributeDefinitions:
      #     - AttributeName: active
      #       AttributeType: B
      #     - AttributeName: platformName
      #       AttributeType: S
      #   KeySchema:
      #     - AttributeName: active
      #       KeyType: HASH
      #     - AttributeName: platformName
      #       KeyType: RANGE
      #   ProvisionedThroughput:
      #     ReadCapacityUnits: 1
      #     WriteCapacityUnits: 1

functions:
  hello:
    handler: handler.hello
